### ISSUE TITLE
Org 1088 has an address, but doesn't show on detail page, and raw metadata is incomplete

### ISSUE THREAD

**Issue by cwd-mparsons** [CredentialEngine/WORKIT-web-site#7]
@siuc-nate 
For org 1088
https://credentialfinder.org/editor/QAOrganization/1088
It has an address and contact point. However the detail page doesn't show the address. 
Related, perhaps, is that the raw metadata does not show all the data from the org. 
While an attempt to publish fails, the payload shows that all the expected data was present

**Comment by siuc-nate** [comment]
This was simply a bug with the way the detail page was being loaded - it has been fixed.
