### ISSUE TITLE
Should we NOT publish properties with default values like false for a boolean, zero for intergers, etc

### ISSUE THREAD

**Issue by cwd-mparsons** [CredentialEngine/WORKIT-web-site#8]
@siuc-nate 
I noticed that for assessment 2116, the metadata includes properties for booleans that were false (see image)
http://ctitest.siuccwd.com/detail/Assessment/2116

![image](https://cloud.githubusercontent.com/assets/26332112/24782674/404957ea-1b0d-11e7-8de4-be56630afde2.png)

These technically should not be published. We should have a means to prevent these 'default' values from being published. 
Thoughts?

**Comment by siuc-nate** [comment]
Interesting question - does the interface provide a way to specify _no_ value? False would be a valid value for those who want to indicate false on any of those fields.

**Comment by cwd-mparsons** [comment]
Certainly this is an issue with the use of check boxes. 
If true/false radio buttons were used, and no value is entered, this could interpreted as meaning to save a null. The user can then explicitly select false. 
With a radio button the user can't unselect. But at least there has be a conscious effort to initially select one or the other.
A better option would to present a third radio button like 'No Answer', or 'Unknown', and set as the default.

**At the very least the issue is that the system is essentially publishing false information**. A user could have missed selecting an option, and now the system is publishing a value as false.

**Comment by cwd-mparsons** [comment]
The editor was updated to provide a not applicable option. The property is initially null. This will be shown as N/A in the editor. Properties with NULL values are not published to the registry.
